# Generated by Django 4.2.16 on 2026-01-01 22:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '__first__'),
        ('agents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be collected', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], help_text='Method used for payment', max_length=20, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, help_text='External transaction reference (e.g., MTN20241228123456)', max_length=255, null=True)),
                ('due_date', models.DateTimeField(help_text='Date when payment is due')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, help_text='Last time a reminder was sent for this collection', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='agents.agent')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='masters.master')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['master', 'status'], name='collections_master__5f2f2e_idx'), models.Index(fields=['agent', 'status'], name='collections_agent_i_216323_idx'), models.Index(fields=['status', 'due_date'], name='collections_status_ca6858_idx'), models.Index(fields=['transaction_reference'], name='collections_transac_e7d96e_idx')],
            },
        ),
    ]
