# Generated by Django 4.2.16 on 2026-01-01 23:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for HMAC webhook signing', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key'], name='masters_mas_api_key_cbea09_idx'), models.Index(fields=['email'], name='masters_mas_email_a0d834_idx'), models.Index(fields=['is_active'], name='masters_mas_is_acti_283da4_idx')],
            },
        ),
    ]
