# Generated by Django 4.2.16 on 2026-01-01 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '__first__'),
        ('agents', '__first__'),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name for internal reference', max_length=255)),
                ('whatsapp_template_name', models.CharField(blank=True, help_text='Name of the approved template in Meta Business Suite', max_length=255, null=True)),
                ('template_type', models.CharField(choices=[('collection_reminder', 'Collection Reminder'), ('payment_confirmation', 'Payment Confirmation'), ('custom', 'Custom')], default='custom', help_text='Type of template', max_length=50)),
                ('content', models.TextField(help_text='Template content with variables like {agent_name}, {amount}, etc.')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Variable definitions (e.g., {"agent_name": "Agent Name", "amount": "Amount"})')),
                ('language_code', models.CharField(default='fr', help_text='Language code (e.g., fr, en)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='masters.master')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], db_index=True, default='pending', max_length=20)),
                ('to_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('from_number', models.CharField(blank=True, help_text='Sender phone number', max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp message ID from API', max_length=255, null=True)),
                ('content', models.TextField(help_text='Message content')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='agents.agent')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='collections.collection')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='masters.master')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['master', 'is_active'], name='whatsapp_wh_master__41e632_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='whatsapp_wh_templat_ad2078_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['master', 'status'], name='whatsapp_wh_master__f72596_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['agent', 'status'], name='whatsapp_wh_agent_i_f76729_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['collection', 'status'], name='whatsapp_wh_collect_e490b9_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['message_id'], name='whatsapp_wh_message_71ff1e_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['to_number', 'status'], name='whatsapp_wh_to_numb_54b800_idx'),
        ),
    ]
