# Generated by Django 4.2.16 on 2026-01-01 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(db_index=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Risk score from 0.0 to 100.0', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='masters.master')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['master', 'whatsapp_number'], name='agents_agen_master__09b654_idx'), models.Index(fields=['master', 'is_active'], name='agents_agen_master__582a2a_idx'), models.Index(fields=['risk_score'], name='agents_agen_risk_sc_03cb91_idx')],
                'unique_together': {('master', 'whatsapp_number')},
            },
        ),
    ]
