# Generated by Django 4.2.16 on 2026-01-01 22:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '__first__'),
        ('agents', '__first__'),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(help_text='When reconciliation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When reconciliation completed', null=True)),
                ('total_payments', models.IntegerField(default=0, help_text='Total payments processed')),
                ('matched_payments', models.IntegerField(default=0, help_text='Number of payments matched')),
                ('unmatched_payments', models.IntegerField(default=0, help_text='Number of payments not matched')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount processed', max_digits=12)),
                ('error_message', models.TextField(blank=True, help_text='Error message if reconciliation failed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('agent', models.ForeignKey(blank=True, help_text='If set, reconciliation was for this agent only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='agents.agent')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='masters.master')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['master', 'status'], name='reconciliat_master__56d7b8_idx'), models.Index(fields=['agent', 'status'], name='reconciliat_agent_i_0ca1e6_idx'), models.Index(fields=['status', 'started_at'], name='reconciliat_status_2a57d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_reference', models.CharField(db_index=True, help_text='External transaction reference (e.g., MTN20241228123456)', max_length=255)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], help_text='Method used for payment', max_length=20)),
                ('received_at', models.DateTimeField(help_text='When payment was received')),
                ('is_matched', models.BooleanField(db_index=True, default=False, help_text='Whether payment has been matched to a collection')),
                ('matched_at', models.DateTimeField(blank=True, help_text='When payment was matched', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='agents.agent')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_matches', to='masters.master')),
                ('matched_collection', models.ForeignKey(blank=True, help_text='Collection this payment was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_matches', to='collections.collection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['master', 'is_matched'], name='reconciliat_master__855ef0_idx'), models.Index(fields=['agent', 'is_matched'], name='reconciliat_agent_i_b938f2_idx'), models.Index(fields=['transaction_reference'], name='reconciliat_transac_f890c4_idx'), models.Index(fields=['is_matched', 'received_at'], name='reconciliat_is_matc_386a8d_idx')],
            },
        ),
    ]
